---
abstract: 'Read a database table into a hash'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0
  Test::Pod: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Table2Hash
provides:
  DBIx::Table2Hash:
    file: lib/DBIx/Table2Hash.pm
    version: 1.17
requires:
  Carp: 0
resources:
  license: http://www.perlfoundation.org/artistic_license_1_0
version: 1.17
