--- #YAML:1.0
name: DBIx-Table2Hash
version: 1.13
author:
  - Ron Savage <ron@savage.net.au>
abstract: Read a database table into a hash
license: artistic
requires:
  Carp: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
provides: {}
generated_by: Module::Build version 0.24
